---
- name: update packages
  ansible.builtin.import_tasks: packages.yml

- name: configure ssh
  ansible.builtin.import_tasks: ssh.yml

- name: disable swap
  ansible.builtin.import_tasks: swapoff.yml
