---
- name: update packages
  ansible.builtin.apt:
    autoclean: true
    autoremove: true
    update_cache: true
    upgrade: safe

- name: check for reboot
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_file

- name: reboot
  ansible.builtin.reboot:
    connect_timeout: 120
    reboot_timeout: 120
  when: reboot_file.stat.exists
