---
- name: add ssh users
  vars:
    password_file: "{{ 'passwords/' + inventory_hostname + '-' + item + '.pass' }}"
    plain_password: "{{ lookup('password', password_file + ' length=' + ssh_password_length | string + ' chars=ascii_letters') }}"
  ansible.builtin.user:
    name: "{{ item }}"
    password: "{{ plain_password | password_hash(ssh_password_hash) }}"
    create_home: true
    update_password: on_create
    append: true
    groups:
      - sudo
    state: present
  loop: "{{ ssh_users }}"

- name: configure sshd
  ansible.builtin.template:
    dest: /etc/ssh/sshd_config.d/10-ssh-settings.conf
    src: ssh-settings.j2
    owner: root
    group: root
    mode: u=rw,g=rw,o=r

- name: restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted
