- name: copy kubeadm init configuration file
  ansible.builtin.template:
    src: kubeadm-config.j2
    dest: "/home/{{ ansible_user }}/kubeadm-config.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u=r,g=r,o=r
