---
- name: configure kernel modules to load on boot
  ansible.builtin.copy:
    src: containerd.conf
    dest: /etc/modules-load.d/
    owner: root
    group: root
    mode: u=rw,g=rw,o=r

- name: allow iptables to see bridged traffic
  ansible.builtin.copy:
    src: 99-kubernetes-cri.conf
    dest: /etc/sysctl.d/
    owner: root
    group: root
    mode: u=rw,g=rw,o=r

- name: configure cgroup driver
  ansible.builtin.copy:
    src: config.toml
    dest: /etc/containerd/
    owner: root
    group: root
    mode: u=rw,g=rw,o=r

- name: reboot
  ansible.builtin.reboot:
    connect_timeout: 120
    reboot_timeout: 120
