---
- name: install containerd prereqs
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    update-cache: true
    state: present

- name: download docker repo key
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    dest: /tmp/docker-pgp-key
    owner: root
    group: root
    mode: u=r,g=r,o=r

- name: add docker repo key
  ansible.builtin.command:
    cmd: >
      gpg --dearmor --output /usr/share/keyrings/docker-archive-keyring.gpg /tmp/docker-pgp-key
    creates: /usr/share/keyrings/docker-archive-keyring.gpg

- name: add docker apt repo
  ansible.builtin.template:
    dest: /etc/apt/sources.list.d/docker.list
    src: docker-repo.j2
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: install containerd
  ansible.builtin.apt:
    name: "containerd.io=1.5.11-1"
    update-cache: true
    state: present
